import {
  BORDER_RADIUS_10,
  BORDER_RADIUS_20,
  FONT_12,
  FONT_14,
  FONT_16,
  FONT_18,
  FONT_20,
  FONT_22,
  FONT_24,
  FONT_26,
  FONT_30,
  FONT_32,
  FONT_35,
  FONT_38,
  HEIGHT_10,
  HEIGHT_141,
  HEIGHT_230,
  HEIGHT_25,
  HEIGHT_30,
  HEIGHT_70,
  HORIZONTAL_10,
  HORIZONTAL_5,
  HORIZONTAL_15,
  HORIZONTAL_SCALE_10,
  VERTICAL_10,
  VERTICAL_20,
  VERTICAL_30,
  VERTICAL_35,
  VERTICAL_8,
  VERTICAL_HORIZONTAL_16,
  VERTICAL_HORIZONTAL_8,
  WIDTH_10,
  WIDTH_0,
  WIDTH_141,
  WIDTH_30,
  HORIZONTAL_12,
  HORIZONTAL_1,
  HORIZONTAL_2,
  HORIZONTAL_150,
  HORIZONTAL_20,
  HORIZONTAL_51,
  HORIZONTAL_40,
  FONT_40,
  HEIGHT_35,
  HEIGHT_40,
  HEIGHT_45,
  HEIGHT_50,
  HEIGHT_48,
  FONT_34,
} from './responsive';
import {NOTOSANS_REGULAR_FONT, OOREDOO_HEAVY_FONT} from './fonts';
import {
  SCREEN_HEIGHT,
  fontPixel,
  heightPixel,
  isTablet,
  tabletMargin,
  widthPixel,
} from './normalizedimension';

import {HEADER_HEIGHT} from '../../commonHelper/utils';
import colors from './colors';

export default {
  viewContainer: {backgroundColor: colors.WHITE, flex: 1},
  container: {},
  innercontainer: {
    flex: 1,
  },
  erorrContainer: {height: SCREEN_HEIGHT - HEADER_HEIGHT},
  price: {
    fontFamily: OOREDOO_HEAVY_FONT,
    fontSize: FONT_24,
    color: colors.OOREDOO_RED,
    alignSelf: 'flex-end',
    lineHeight: FONT_34,
  },
  currencyContainer: {
    height: isTablet ? HEIGHT_30 : HEIGHT_45,
    flexDirection: 'row',
  },
  currency: {
    fontFamily: OOREDOO_HEAVY_FONT,
    fontSize: FONT_24,
    color: colors.OOREDOO_RED,
    alignSelf: 'flex-end',
    lineHeight: FONT_34,
    marginHorizontal: HORIZONTAL_5,
  },
  currencydet: {
    fontFamily: OOREDOO_HEAVY_FONT,
    fontSize: FONT_18,
    color: colors.OOREDOO_RED,
    alignSelf: 'flex-end',
    lineHeight: FONT_26,
    marginHorizontal: HORIZONTAL_5,
  },
  buyContainer: {
    shadowOpacity: 0.2,
    shadowColor: colors.GREY,
    backgroundColor: colors.WHITE,
    shadowRadius: BORDER_RADIUS_10,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: isTablet ? tabletMargin() + HORIZONTAL_12 : WIDTH_10,
    padding: VERTICAL_HORIZONTAL_16,
    bottom: VERTICAL_30,
    height: HEIGHT_70,
    alignItems: 'center',
  },
  imgStyle: {height: HEIGHT_141, width: WIDTH_141},
  imgContainer: {
    height: HEIGHT_230,
    alignItems: 'center',
    paddingTop: VERTICAL_35,
  },
  descContainer: {
    flex: 1,
    marginHorizontal: WIDTH_10,
    marginTop: HEIGHT_10,
  },
  btn: {
    borderWidth: 1,
    borderColor: 'red',
    width: widthPixel(134),
    height: heightPixel(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.OOREDOO_RED,
    borderRadius: BORDER_RADIUS_20,
    paddingHorizontal: heightPixel(12),
    alignSelf: 'center',
  },
  btnBundle: {
    borderWidth: 1,
    borderColor: 'red',
    width: widthPixel(134),
    height: heightPixel(40),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -HORIZONTAL_20,
    backgroundColor: colors.OOREDOO_RED,
    borderRadius: BORDER_RADIUS_20,
    paddingHorizontal: heightPixel(12),
    alignSelf: 'center',
  },
  btntext: {
    color: colors.WHITE,
    fontSize: FONT_12,
    lineHeight: FONT_20,
    fontFamily: OOREDOO_HEAVY_FONT,
    textAlign: 'center',
  },
  viewbtn: {
    alignItems: 'flex-end',

    alignContent: 'center',
    width: widthPixel(150),
    justifyContent: 'center',
  },
  viewprice: {
    flexDirection: 'row',
    alignItems: 'center',
    width: widthPixel(150),
    paddingVertical: heightPixel(21),
  },
  viewpcard: {
    width: widthPixel(351),
    marginHorizontal: widthPixel(12),
    height: heightPixel(70),
    backgroundColor: colors.WHITE,
    borderRadius: 10,
    paddingHorizontal: widthPixel(16),
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  viewimgcard: {
    marginHorizontal: WIDTH_30,
    marginVertical: HEIGHT_30,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shadowView: {
    marginBottom: VERTICAL_20,
  },
  title: {
    fontSize: FONT_24,
    lineHeight: FONT_40,
    fontFamily: OOREDOO_HEAVY_FONT,
    color: colors.OOREDOO_BLACK,
    marginBottom: heightPixel(27),
    textAlign: 'left',
    marginEnd: heightPixel(50),
  },
  detailHeader: {
    fontSize: FONT_14,
    lineHeight: FONT_24,
    fontFamily: OOREDOO_HEAVY_FONT,
    color: colors.LIGHT_BLACK,
    marginBottom: HEIGHT_10,
    textAlign: 'left',
  },
  details: {
    fontSize: FONT_16,
    lineHeight: FONT_26,
    fontFamily: NOTOSANS_REGULAR_FONT,
    color: colors.OOREDDO_GREY,
    marginBottom: HEIGHT_10,
    textAlign: 'left',
  },
  morediscountview: {
    flexDirection: 'row',
    marginHorizontal: widthPixel(5),
  },
  morecurview: {
    flexDirection: 'row',
  },
  moreTextstrike: {
    color: colors.OOREDDO_LIGHT_GREY,
    fontFamily: OOREDOO_HEAVY_FONT,
    fontSize: FONT_24,
    lineHeight: FONT_32,
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    alignSelf: 'flex-end',
  },
  vulike: {
    marginVertical: HEIGHT_10,
    marginHorizontal: isTablet ? tabletMargin() + WIDTH_10 : WIDTH_10,
    flex: 1,
  },
  ulike: {
    fontSize: FONT_22,
    lineHeight: FONT_38,
    fontFamily: NOTOSANS_REGULAR_FONT,
    color: colors.BLACK,
    textAlign: 'left',
    marginVertical: HEIGHT_25,
  },
  lineStyle: {
    height: 1,
    backgroundColor: isTablet ? colors.DARK_GREY : colors.LIGHT_GREY,
    marginHorizontal: isTablet ? tabletMargin() + WIDTH_10 : VERTICAL_10,

    marginVertical: HEIGHT_10,
  },
  schedulerenewalTopView: {
    marginVertical: VERTICAL_10,
    padding: VERTICAL_HORIZONTAL_8,
    paddingHorizontal: HORIZONTAL_SCALE_10,
    flexDirection: 'row',
  },
  schedulerenewalView: {
    paddingHorizontal: isTablet ? tabletMargin() : HORIZONTAL_10,
  },
  schedulerenewalLabel: {
    fontSize: FONT_14,
    fontFamily: OOREDOO_HEAVY_FONT,
    color: colors.BLACK,
    textAlign: 'left',
    lineHeight: FONT_24,
  },
  schedulerenewalDescLabel: {
    fontSize: FONT_14,
    marginEnd: HORIZONTAL_10,
    fontFamily: NOTOSANS_REGULAR_FONT,
    color: colors.BLACK,
    letterSpacing: -0.12,
    textAlign: 'left',
    lineHeight: FONT_24,
    marginTop: VERTICAL_8,
  },
  switchContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginLeft: -HORIZONTAL_10,
    marginRight: isTablet ? tabletMargin() : HORIZONTAL_1,
  },
  btnfull: {
    borderWidth: 1,
    borderColor: 'red',
    width: widthPixel(320),
    height: heightPixel(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.OOREDOO_RED,
    borderRadius: BORDER_RADIUS_20,
    paddingHorizontal: heightPixel(12),
    alignSelf: 'center',
  },
  btnfullcontinue: {
    width: widthPixel(351),
    height: heightPixel(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.OOREDOO_RED,
    borderRadius: BORDER_RADIUS_20,
    paddingHorizontal: heightPixel(12),
    alignSelf: 'center',
    marginTop: HEIGHT_10,
  },
  imgContainerbg: {
    height: heightPixel(280),
    alignItems: 'center',
  },
  umaylikecontent: {
    marginHorizontal: isTablet ? tabletMargin() + HORIZONTAL_10 : 0,
  },
  separator: {
    height: 1,
    backgroundColor: colors.LINE_LIGHT_GRAY,
    marginHorizontal: isTablet ? tabletMargin() : HORIZONTAL_10,
    marginTop: VERTICAL_30,
  },
  shadowbuyContainer: {
    backgroundColor: colors.WHITE,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: isTablet ? tabletMargin() : WIDTH_10,
    padding: VERTICAL_HORIZONTAL_16,
    bottom: VERTICAL_30,
    height: HEIGHT_70,
    elevation: 4,
  },
  shadowMain:{
    flexDirection:'row',
    alignItems:'center'
  }
};
