export const Site_Assist = {
  AvailableOffers: [
    {
      serviceid: '826144975fb244efb34693cfb2054dda_1994802',
      offerid: '826144975fb244efb34693cfb2054dda_1994802',
      servicetype: 'INTERACTIVE',
      servicecode: '1994802',
      name: 'Create your own bundle',
      description: 'Create your own Voice and Data bundle',
      validity: null,
      stepdatavalue: '1',
      stepvoicevalue: '4',
      status: 'I',
      statusdesc: 'INTERACTIVE',
      image: '/pmsapi/pmsapi/Banner/Getimage?id=&l=en',
      webimage: '/pmsapi/pmsapi/Banner/Getimage?id=&l=en',
      visible: false,
      popup: {
        title: 'Confirmation',
        activate_message: null,
        deactivate_message: null,
        activate_button: 'Continue',
        deactivate_button: 'Cancel',
        cancel_button: 'Cancel',
        confirmation: true,
        openurl: false,
        confirm_url: '',
      },
      expirationdate: '2021-03-17 00:00:00',
      effectivedate: '2021-02-14 00:08:11',
      position: 0,
      title: 'Create your own bundle',
      actionbutton: 'Subscribe',
      category: 'MySurprise',
      subcategory: 'Bundle',
      lockunlock: false,
      unlockimage: '',
      actiontype: null,
      external: 'F',
      maxgb: '20',
      maxmins: '60',
      maxvalidity: '30',
      minmins: '5',
      minvalidity: '7',
      mingb: '5',
      validityrange: [7, 15, 30, 60, 90],
      pricepergb: '0.0069412',
      priceperminute: '0.0031',
      redeemflag: 'N',
      tid: '826144975fb244efb34693cfb2054dda',
      totalavailablecoins: '0',
      servicenode: null,
      chargeamount: null,
      planid: null,
      isreccurent: null,
      iscancellable: null,
      languagecode: null,
      operation: null,
      sequenceno: null,
      amount: '',
      usage: null,
      ctype: null,
      isitsurpriseoffer: false,
      redeemcoins: false,
      refcode: '',
      transdate: '',
      group: '',
      group_position: -1,
      showindisablemode: false,
      offercode: '1994802',
    },
  ],
};
